name: Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 8.10.0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Zip extensions
        run: |
          pnpm zip
          mv .output/*-chrome.zip .output/tailname-chrome.zip
          pnpm zip:firefox
          mv .output/*-firefox.zip .output/tailname-firefox.zip

      - name: Create and push tag
        id: create_and_push_tag
        run: |
          TAG=auto-release-$(git rev-parse --short HEAD)
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag $TAG
          git push origin $TAG

      - name: Create GitHub Release and upload ZIPs
        uses: ncipollo/release-action@v1
        with:
          artifacts: ".output/tailname-chrome.zip,.output/tailname-firefox.zip"
          generateReleaseNotes: true
          tag: ${{ steps.create_and_push_tag.outputs.TAG }}
